server:
  port: 8080

# 2-3-1 yml文件中编写Eureka-client配置(每个eureka-client必须包含application.name属性)
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka



spring:
  application:
    name: orderservice

  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


# 3-1-2 配置文件中对指定微服务配置单独的负责均衡规则
userservice:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 3-2 Ribbon开启饥饿加载
ribbon:
  eager-load:
    enabled: true         # 开启饥饿加载
    clients:
     - userservice  # 指定对userservice服务进行饥饿加载

mybatis:
#  type-aliases-package: com.hui.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
